# ===============================
# JWT Security Configuration
# ===============================
# A 256-bit base64 encoded secret key used to sign the token.
# In a real production app, this should be an environment variable.
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Token expiration time in milliseconds (86400000 ms = 24 hours)
app.jwt.expiration-ms=86400000